par(mfrow=c(1,1))
quartz(dpi=72)
dotchart(sejong.poll.high$counts,groups=factor(sejong.poll.high$region),labels=sejong.poll.high$vote, main="대신, 관찰사, 도사")
quartz(dpi=72)
dotchart(sejong.poll.chief$counts,groups=factor(sejong.poll.chief$region),labels=sejong.poll.chief$vote, main="수령")
quartz(dpi=72)
dotchart(sejong.poll.3rd$counts,groups=factor(sejong.poll.3rd$region),labels=sejong.poll.3rd$vote, main="3품이하현직")
quartz(dpi=72)
dotchart(sejong.poll.3rd.ex$counts,groups=factor(sejong.poll.3rd.ex$region),labels=sejong.poll.3rd.ex$vote, main="3품이하전직")
quartz(dpi=72)
dotchart(sejong.poll.ordinary$counts,groups=factor(sejong.poll.ordinary$region),labels=sejong.poll.ordinary$vote, main="품관, 촌민")
