---
title: "Sejong_poll_kr"
author: "coop711"
date: "2015년 3월 18일"
output: html_document
---

Data Arrange
------------

- Data input

```{r}
rm(list=ls())
load("sejong_poll_kor.rda")
ls()
```

- Data 

```{r}
sejong.poll
```

- Factor Declaration

```{r}
sejong.poll.2<-sejong.poll
sejong.poll.2$vote<-factor(sejong.poll.2$vote,levels=c("yes","no"),labels=c("찬성","반대"))
sejong.poll.2$class<-factor(sejong.poll.2$class,levels=c("high","chief","third.current","third.ex","ordinary"),labels=c("대신 등","수령", "3품이하현직","3품이하전직","품관촌민"))
sejong.poll.2$region<-factor(sejong.poll.2$region,levels=c("Seoul","yuhu","gyunggi","pyungan","hwanghae","chungcheong","kangwon","hamgil","gyungsang","jeolla"),labels=c("서울","유후사","경기","평안","황해","충청","강원","함길","경상","전라"))
sejong.poll.kr<-sejong.poll.2
sejong.poll.kr
```

- Cross Tables

```{r}
attach(sejong.poll.kr)
xtabs(counts~vote, data=sejong.poll.kr)
xtabs(counts~class, data=sejong.poll.kr)
xtabs(counts~region, data=sejong.poll.kr)
xtabs(counts~vote+class, data=sejong.poll.2)
xtabs(counts~vote+region, data=sejong.poll.2)
xtabs(counts~vote+class+region, data=sejong.poll.2)
ftable(xtabs(counts~vote+class+region, data=sejong.poll.2))
```

- 찬반을 색깔로 구분. 우선, sejong.poll.kr 을 search 라이브러리에서 분리후 작업.

```{r}
detach(sejong.poll.kr)
sejong.poll.kr$color[sejong.poll.kr$vote=="찬성"]<-"blue"
sejong.poll.kr$color[sejong.poll.kr$vote=="반대"]<-"red"
sejong.poll.kr
```

- 규모에 따라 "품관촌민"과 다른 계급을 분리하여 분석. !의 용도에 대하여 숙지.

```{r}
attach(sejong.poll.kr)
ordinary<-class=="품관촌민"
ordinary
sejong.poll.kr.ordinary<-sejong.poll.kr[ordinary,]
sejong.poll.kr.ordinary
sejong.poll.kr.officers<-sejong.poll.kr[!(ordinary),]
sejong.poll.kr.officers
```

- 각 계급집단에 대하여 지역별 찬반을 dotchart 로 표현

```{r fig.width=8, fig.height=8}
dotchart(xtabs(counts~vote+region,data=sejong.poll.kr.officers)[2:1,], color=color, main="관료집단")
```

```{r fig.width=8, fig.height=8}
dotchart(xtabs(counts~vote+region,data=sejong.poll.kr.ordinary)[2:1,], color=color, main="품관촌민")
```

- 관료집단 중 서울의 상황을 보다 상세히 그려보면, pch=17 의 효과 검토.

```{r fig.width=7, fig.height=7}
detach()
attach(sejong.poll.kr.officers)
xtabs(counts~vote+class, data=sejong.poll.kr.officers[region=="서울",])[2:1,]
dotchart(xtabs(counts~vote+class,data=sejong.poll.kr.officers[region=="서울",])[2:1,], color=color, pch=17, main="서울")
```
